services:
  - type: web
    name: radar-bjj
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATA_DIR
        value: /var/data
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: RESEND_API_KEY
        sync: false
      - key: URL_SITE
        value: https://radar-bjj.onrender.com
    disk:
      name: radar-bjj-data
      mountPath: /var/data
      sizeGB: 1
